const bestData = [
  {
    id: 0,
    src: "/images/best1.jpg",
    best: "BEST",
    title: "꼬불이어묵  진미꼬치(500g)",
    discount: 17,
    sale_price: 10000,
    price: "12,000원",
    deliveryFee: "무료",
  },
  {
    id: 1,
    src: "/images/best2.jpg",
    best: "BEST",
    title: "생선살88% 수제명태봉어묵(500g)",
    discount: 10,
    sale_price: 9000,
    price: "10,000원",
    deliveryFee: "무료",
  },
  {
    id: 2,
    src: "/images/best3.jpg",
    best: "BEST",
    title: "얆은 사각어묵 상천(800g)",
    discount: 13,
    sale_price: 14000,
    price: "16,000원",
    deliveryFee: "무료",
  },
  {
    id: 3,
    src: "/images/best4.jpg",
    best: "BEST",
    title: "밀가루제로 수제모듬어묵(700g)",
    discount: 15,
    sale_price: 12000,
    price: "14,000원",
    deliveryFee: "무료",
  },
  {
    id: 4,
    src: "/images/best5.jpg",
    best: "BEST",
    title: "야채어묵 나뭇잎(소)(대)",
    discount: 37,
    sale_price: 3500,
    price: "5,500원",
    deliveryFee: "무료",
  },
  {
    id: 5,
    src: "/images/best6.jpg",
    best: "BEST",
    title: "구운어묵 진금죽어묵(280g)",
    discount: 15,
    sale_price: 12000,
    price: "14,000원",
    deliveryFee: "무료",
  },
  {
    id: 6,
    src: "/images/best7.jpg",
    best: "BEST",
    title: "종합모듬어묵(1000g)",
    discount: 15,
    sale_price: 12000,
    price: "14,000원",
    deliveryFee: "무료",
  },
  {
    id: 7,
    src: "/images/best8.jpg",
    best: "BEST",
    title: "수제어묵 고로케(700g)",
    discount: 15,
    sale_price: 12000,
    price: "14,000원",
    deliveryFee: "무료",
  },
  {
    id: 8,
    src: "/images/best9.jpg",
    best: "BEST",
    title: "생선살88% 수제카레어묵(500g)",
    discount: 22,
    sale_price: 9000,
    price: "11,500원",
    deliveryFee: "무료",
  },
  {
    id: 9,
    src: "/images/best10.jpg",
    best: "BEST",
    title: "생선살88% 수제치즈어묵(500g)",
    discount: 22,
    sale_price: 9000,
    price: "11,500원",
    deliveryFee: "무료",
  },
  {
    id: 10,
    src: "/images/best11.jpg",
    best: "BEST",
    title: "생선살88% 수제오징어어묵(500g)",
    discount: 22,
    sale_price: 9000,
    price: "11,500원",
    deliveryFee: "무료",
  },
  {
    id: 11,
    src: "/images/best12.jpg",
    best: "BEST",
    title: "수제치즈볼어묵(210g)",
    discount: 19,
    sale_price: 4500,
    price: "5,500원",
    deliveryFee: "무료",
  },
];

export default bestData;
