const reviewData = [
  {
    id: 0,
    src: "/images/best1.jpg",
    num: 10,
    title: "맛있게 잘먹습니다! 재구매 의사 100%",
    name: "한**",
    date: "2022-12-22",
  },
  {
    id: 1,
    src: "/images/best2.jpg",
    num: 9,
    title: "배송빠르고 잘먹었습니다!!",
    name: "박**",
    date: "2022-11-21",
  },
  {
    id: 2,
    src: "/images/best3.jpg",
    num: 8,
    title: "맛있어요. 배송 빠르네요!!",
    name: "김**",
    date: "2022-11-11",
  },
  {
    id: 3,
    src: "/images/best4.jpg",
    num: 7,
    title: "아이들 간식으로 딱이에요!!",
    name: "이**",
    date: "2022-10-18",
  },
  {
    id: 4,
    src: "/images/best5.jpg",
    num: 6,
    title: "겨울철에 자주 시켜먹습니다 ㅎㅎ",
    name: "소**",
    date: "2022-10-03",
  },
  {
    id: 5,
    src: "/images/best6.jpg",
    num: 5,
    title: "언제 먹어도 맛있는 범표어묵!!",
    name: "김**",
    date: "2022-9-15",
  },
  {
    id: 6,
    src: "/images/best7.jpg",
    num: 4,
    title: "항상 잘 이용하고 있습니다~~",
    name: "문**",
    date: "2022-9-10",
  },
  {
    id: 7,
    src: "/images/best8.jpg",
    num: 3,
    title: "앞으로도 계속 이용예정!! 맛도 양도 굿굿!!",
    name: "정**",
    date: "2022-8-24",
  },
  {
    id: 8,
    src: "/images/best9.jpg",
    num: 2,
    title: "맛있어요!! 가족들이 좋아하네요~",
    name: "강**",
    date: "2022-8-23",
  },
  {
    id: 9,
    src: "/images/best10.jpg",
    num: 1,
    title: "조리도 간편하고 반찬, 간식 다용도로 이용할 수 있어 좋아요!!",
    name: "최**",
    date: "2022-7-22",
  },
];

export default reviewData;
